### ISSUE TITLE
[Bug] Unable to install latest release - Incompatable with Zotero 6 

### ISSUE THREAD

**Issue by JonazM** [windingwind/zotero-actions-tags#144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 11
- Zotero Version: Zotero 6
- Plugin Version: Latest

### Describe the bug

I can't install the latest plugin because I am using Zotero 6. 

### Debug Output

N/A

### Anything else?

Is there a way for me to get a older version so I can use it with Zotero 6? I have other plugins installed that I really need for my notetaking and reading at night and these are not updated to Zotero 7 because is currently beta.

**Comment by windingwind** [comment]
Please install <1.0.0 for Z6

**Comment by windingwind** [comment]
See readme#install

**Comment by JonazM** [comment]
Hi,
Thanks for the reference. I just wanted to point out that the way your
readme reads is a bit vague and difficult to follow. I personally think I
should have to click on the drop down menu that says More versions.
Instead, I would probably just have the listed links and have a specific
tag associated with it the link that shows which version is for. I think
that this might save you a few more emails asking/reporting this issue.

Also,  the : v0.3.0 (last for Zotero 6) link under More versions does not
work. I happened to click on Latest Stable and guessed that it was for
Zotero 6 instead of 7 because your .xpi name was different and because I
have seen that name before (from videos I watched as references).

I find the same issue trying to just get the latest version for the Zotero
7 plugin: having to click on assets (which doesn't make sense to someone
who is not familiar with GitHub) to get the file acts as a wall and hard to
see the file that people wants to get to.

I hope that you my comments are not taken in a negative way and instead as
a constructive criticism that would help the community at large. I am sure
that there are a lot of people who would love to use your plugin and are
not familiar with the GitHub navigation system. I am happy to help you in
any way possible, if you think that would be useful for you.

Cheers,

-Jonaz M.

**Comment by windingwind** [comment]
Thanks for the reply. If 0.3.0 does not work for you, are you installing the correct `xpi` file? The 0.3.0 has been out for months and is not likely to be incompatible with Z6.

>  having to click on assets (which doesn't make sense to someone
who is not familiar with GitHub) to get the file acts as a wall and hard to
see the file that people wants to get to.

Unfortunately, this is how github works and is something I cannot control.

> I just wanted to point out that the way your
readme reads is a bit vague and difficult to follow.

I am not a native English speaker. Welcome contributions like updating the readme, writing doc, or making videos - that's why we call it open source.

Thanks for your suggestions and I value them very much,

best
