### ISSUE TITLE
[Bug] Export tags fails

### ISSUE THREAD

**Issue by fflamerie** [windingwind/zotero-actions-tags#148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS:  Windows 10 Professional
- Zotero Version: 6.0.27
- Plugin Version: 0.3.0

### Describe the bug

When I try to export tags, the process is launched but never ends up.
The  dialog attached below remains displayed.

Steps :
1. Select "My library"
2. Right-click and select "Manage tags"
3. Export Tags > OK

![zotero_tag_export_pending](https://github.com/windingwind/zotero-actions-tags/assets/33718229/f43965de-2fa3-434b-b93e-58e7c14cd86d)

### Debug Output

version => 6.0.27, platform => Win32, oscpu => Windows NT 10.0; WOW64, locale => fr-FR, appName => Zotero, appVersion => 6.0.27, extensions => Zotero Tag (0.3.0, extension), Zotero LibreOffice Integration (6.0.4.SA.6.0.27, extension), Zotero Word for Windows Integration (6.0.3.SA.6.0.27, extension), Zotero Open Citations (0.3.0, extension, disabled), Storage Scanner for Zotero (5.0.11, extension, disabled), DOI Manager (1.4.2, extension, disabled), Zotero Report Customizer (5.0.38, extension, disabled), Duplicates Merger for Zotero (1.1.5, extension, disabled), ZoteroPreview (0.1.6, extension, disabled), Zotodo (0.10.1, extension, disabled), Zotero Style (2.6.7, extension, disabled), Zotero PDF Translate (1.0.23, extension, disabled), ZotFile (5.1.2, extension, disabled), PMCID fetcher for Zotero (0.0.26, extension, disabled), Better BibTex for Zotero (6.7.122, extension, disabled), Zutilo Outil pour Zotero (3.10.0, extension, disabled)

(3)(+0095572): ZoteroTag: Updating Selected items

(3)(+0001227): itemTree.render(). Displaying Item Tree

(4)(+0010739): SELECT A.itemID FROM items A WHERE 1 AND A.itemID NOT IN (SELECT itemID FROM deletedItems) AND libraryID=? [1]

(3)(+0000044): Zotero.Libraries.getName() is deprecated. Use Zotero.Library.prototype.name instead

**Comment by windingwind** [comment]
Unfortunately, only the latest version of this plugin (currently it is a prerelease for Zotero 7) is maintained. This export tags feature has been removed in the latest version since the plugin provides a new feature called `script actions` to enable running custom scripts, e.g. export/import tags. This feature will need to be supported by a 3rd party script (written by someone else or me), not integrated natively into this plugin.

Sorry, I cannot solve this bug. Alternative solutions are:

1. Move to Zotero 7 and push me to write a script, though that might take a while
2. Write JS code to export tags
3. Provide more detailed steps to reproduce, like selecting 1 or 2 items in the library and trying to export tags. Does this still happen?

**Comment by fflamerie** [comment]
Sorry, I miss your comment... Thank for your help. I will wait for Zotero 7.
